### ISSUE TITLE
Wrong swipe back after token creation

### ISSUE THREAD

**Issue by dtonon** [cashubtc/eNuts#194] opened 2023-09-10 15:34 UTC
**Describe the bug**
After creating a token, if the user in the last view swipes back, he is brought back to the "Cashu is beeing created" view.

**To Reproduce**
1. Use Send and create a token
2. In the last view swipe back (right to left from the right edge) 

**Expected behavior**
The user should be brought to the home.

**Desktop (please complete the following information):**
 - OS: Android
 - Version apk 0.3.0

**Comment by KKA11010** [comment] 2023-09-11 15:35
Oh ok thank you for the hint 🥇

**Comment by swedishfrenchpress** [comment] 2023-09-13 21:15
I was able to reproduce this on Android but not on iOS. Android has that unique "swipe right to left" to go back. 
![Screenshot_20230913-231410](https://github.com/cashubtc/eNuts/assets/78821053/cb1a1dda-f789-4dd4-86fd-d7ff6435c044)
![Screenshot_20230913-231414](https://github.com/cashubtc/eNuts/assets/78821053/49aff5ca-56ee-47cf-a5a7-b18b6f8de1bf)

**Comment by swedishfrenchpress** [comment] 2023-09-16 13:35
Looks like this has been fixed in the latest version @KKA11010 
https://github.com/cashubtc/eNuts/assets/78821053/c747529d-aec9-4a41-ac95-ead373ba8ab4

**Comment by KKA11010** [comment] 2023-09-16 13:37
> Looks like this has been fixed in the latest version @KKA11010 https://github.com/cashubtc/eNuts/assets/78821053/c747529d-aec9-4a41-ac95-ead373ba8ab4

Ok, Thank you for testing out 🥇

**Comment by swedishfrenchpress** [comment] 2023-09-16 13:42
Tested in following screens too. It worked on the following three:
- new cashu token
- success screen
- processing screen (the loading screen right before success or new cashu token)

However, I wasn't able to test on the dashboard.
- dashboard (was going back to PIN screen) 
I think because I'm running eNuts on the Expo Go app i can't fully test this. When I swipe back it takes to me the ExpoGo app screen.

**Comment by KKA11010** [comment] 2023-09-16 13:44
> Tested in following screens too. It worked on the following three:
> 
>     * new cashu token
> 
>     * success screen
> 
>     * processing screen (the loading screen right before success or new cashu token)
> 
> 
> However, I wasn't able to test on the dashboard.
> 
>     * dashboard (was going back to PIN screen)
>       I think because I'm running eNuts on the Expo Go app i can't fully test this. When I swipe back it takes to me the ExpoGo app screen.

It is the correct behavior, it does not take you from dashboard back to the pin screen but out of the app and that is ok i guess 👍

**Closed** 2023-09-16 15:13 UTC
Labels: bug, Android, IOS, completed 🌟
